app:
  version: 1.0.0
  title: Leap

spring:
  profiles:
    include:
      - springdoc
---

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/leap
    username: root
    password: admin
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    database: POSTGRESQL
#    hibernate:
#      ddl-auto: update
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /api