app:
  version: 1.0.0
  title: Leap

spring:
  profiles:
    include:
      - springdoc
---

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  management:
    endpoints:
      enabled-by-default: false
      web:
        base-path: /
      exposure:
        include: health
      endpoint:
        health:
          enabled: true
          group:
            liveness:
              include: livenessState, ping
            readiness:
              include: reasinessState
            show-details: "NEVER"
            probles:
              enable: true
      health:
        ping:
          enabled: true
        diskspace:
          enabled: true
        livenessState:
          enabled: true
        readnessState:
          enabled: true
        servicosDependentes:
          enabled: false
        circuitbreakers:
          enabled: false

server:
  port: 8081
  servlet:
    context-path: /api