spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/leap
    username: root
    password: admin
    jpa:
#      open-in-view: false
      hibernate.ddl-auto: validate
      database: POSTGRESQL
      show-sql: true

---

jwt:
  key: "bGliZXJkYWRlX2ZpbmFuY2VpcmFfdHJhbnNwYXJlbmNpYV9nZXJhX2NvbmZpYW5jYQ=="

brapiFindTicket: "https://brapi.dev/api/quote"
